# Generated by Django 3.2.5 on 2021-07-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenantid', models.CharField(max_length=60)),
                ('expdate', models.DateTimeField()),
                ('increasedate', models.DateTimeField()),
                ('increasepercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('salestax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('utilities', models.DecimalField(decimal_places=2, max_digits=10)),
                ('managementfee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
