# Generated by Django 3.2.5 on 2021-07-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbsapi', '0002_auto_20210723_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contractid',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='ownerid',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='propertyid',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
