# Generated by Django 3.2.5 on 2021-07-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbsapi', '0003_auto_20210723_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerid', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('phonenumber', models.CharField(max_length=60)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenantid', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
