# Generated by Django 3.2.5 on 2021-07-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbsapi', '0004_owner_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='id',
        ),
        migrations.AlterField(
            model_name='owner',
            name='ownerid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tenantid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
