# Generated by Django 3.2.5 on 2021-07-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbsapi', '0006_auto_20210723_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='ownerid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='tenantid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
