# Generated by Django 3.2.5 on 2021-07-24 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbsapi', '0007_auto_20210724_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='ownerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbsapi.owner'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tenantid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbsapi.tenant'),
        ),
    ]
