# Generated by Django 3.2.5 on 2021-07-24 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbsapi', '0011_alter_contract_tenantid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='name',
            new_name='tenantname',
        ),
        migrations.AlterField(
            model_name='contract',
            name='tenantid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbsapi.tenant'),
        ),
    ]
