# Generated by Django 3.2.5 on 2021-07-24 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbsapi', '0012_auto_20210724_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='tenantid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='bbsapi.tenant'),
        ),
    ]
