# Generated by Django 3.2.5 on 2021-07-25 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbsapi', '0014_rename_tenantname_tenant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('sitenumber', models.CharField(max_length=60)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='propertyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbsapi.property'),
        ),
    ]
