# Generated by Django 3.2.5 on 2021-07-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbsapi', '0015_auto_20210725_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='propertyid',
            field=models.CharField(max_length=60),
        ),
    ]
