# Generated by Django 3.2.5 on 2021-07-25 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbsapi', '0017_alter_contract_propertyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='propertyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbsapi.property'),
        ),
    ]
